{
    'name': 'Construction',
    'version': '1.0',
    'category': 'Construction',
    'depends': [
        'base_industry_data',
        'crm_enterprise',
        'documents',
        'helpdesk',
        'industry_fsm_stock',
        'knowledge',
        'purchase_stock',
        'sale_crm',
        'sale_margin',
        'sale_project_forecast',
        'web_studio',
    ],
    'data': [
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_access.xml',
        'data/ir_model_fields.xml',
        'data/ir_default.xml',
        'data/ir_actions_server.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_embedded_actions.xml',
        'data/ir_ui_menu.xml',
        'data/qweb_view.xml',
        'data/base_automation.xml',
        'data/documents_folder.xml',
        'data/res_config_settings.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/ir_attachment_pre.xml',
        'data/uom_uom.xml',
        'data/planning_role.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/mail_activity_type.xml',
        'data/hr_job.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/x_work_item.xml',
        'data/x_work_item_line.xml',
    ],
    'demo': [
        'demo/documents_folder.xml',
        'demo/res_partner.xml',
        'demo/project_project.xml',
        'demo/documents_document.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/resource_resource.xml',
        'demo/crm_lead.xml',
        'demo/product_supplierinfo.xml',
        'demo/stock_quant.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/sale_order_confirm.xml',
        'demo/project_task.xml',
        'demo/mail_activity.xml',
        'demo/account_analytic_line.xml',
        'demo/project_update.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/purchase_order_confirm.xml',
        'demo/planning_recurrency.xml',
        'demo/planning_slot.xml',
        'demo/sale_order_spreadsheet.xml',
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/qweb_view.xml",
        "data/res_config_settings.xml",
        "static/src/widgets/apply_to_section_widget.xml",
        "static/src/widgets/apply_to_section_widget.js",
    ],
    'assets': {
        'web.assets_backend': [
            'construction/static/src/widgets/apply_to_section_widget.js',
            'construction/static/src/widgets/apply_to_section_widget.xml',
        ],
    },
    'images': ['images/main.png'],
    'url': "https://www.odoo.com/trial?industry&selected_app=construction",
    'website': "https://www.odoo.com/industries/construction",
}
