{
    "name": "Studio customizations",
    "version": "19.0.1.0",
    "category": "Studio",
    "author": "Odoo Library",
    "depends": [
        "base_industry_data",
        "mrp_account",
        "pos_event",
        "project_sale_subscription",
        "sale_crm",
        "website_event_sale",
        "website_knowledge",
    ],
    "data": [
        "data/ir_attachment_pre.xml",
        "data/event_event.xml",
        "data/knowledge_cover.xml",
        "data/knowledge_article.xml",
        "data/knowledge_article_favorite.xml",
        'data/ir_ui_menu.xml',
        "data/pos_category.xml",
        "data/product_category.xml",
        "data/product_public_category.xml",
        "data/product_template.xml",
        "data/product_product.xml",
        "data/product_pricelist.xml", 
        "data/pos_config.xml",
        "data/product_pricelist_item.xml",
        "demo/website_view.xml",
        "demo/resource_resource.xml",
        "demo/res_partner.xml",
        "demo/pos_session.xml",
        "demo/pos_order.xml",
        "demo/pos_order_line.xml",
        "demo/sale_order.xml",
        "demo/sale_order_line.xml",
        "demo/stock_quant.xml",
        "demo/website_page.xml",
        "demo/website_menu.xml",
        "demo/pos_config.xml",
        "demo/website_theme_apply.xml",
        "demo/sale_order_confirm.xml",
        "demo/website.xml",
    ],
    "demo": [
        
    ],
    "license": "OPL-1",
}
