{
    "name": "Library",
    "version": "19.0.1.0",
    "category": "Studio",
    "author": "Odoo Library",
    "depends": [
        'ai_documents',
        'base_industry_data',
        'crm',
        'documents_account',
        'documents_fsm',
        'documents_spreadsheet',
        'event_product',
        'industry_fsm_sale_report',
        'knowledge',
        'mass_mailing',
        'mrp_account',
        'pos_online_payment_self_order',
        'purchase_stock',
        'sale_planning',
        'sale_subscription',
        'sign',
        'stock_barcode',
        'stock_barcode_barcodelookup',
        'web_studio',
        'website_appointment_sale_project',
        'website_sale_loyalty',
        'website_sale_stock',
    ],
    "data": [
        "data/res_config_settings.xml",
        "data/ir_attachment_pre.xml",
        "data/event_event.xml",
        "data/knowledge_cover.xml",
        "data/knowledge_article.xml",
        "data/knowledge_article_favorite.xml",
        "data/ir_filters.xml",
        "data/ir_model_fields.xml", 
        'data/stock_route.xml',
        'data/stock_location.xml',
        'data/stock_picking_type.xml',
        "data/ir_ui_view.xml",
        "data/ir_actions_act_window.xml",
         "data/ir_actions_server.xml",
        "data/base_automation.xml",
        "data/ir_ui_menu.xml",
        "data/pos_category.xml",
        "data/product_category.xml",
        "data/product_public_category.xml",
        "data/product_template.xml",
        "data/product_product.xml",
        "data/product_pricelist.xml",
        "data/stock_rule.xml",
        "data/pos_config.xml",
        "data/product_pricelist_item.xml",
        "demo/website_view.xml",
        "demo/resource_resource.xml",
        "demo/res_partner.xml",
        "demo/pos_session.xml",
        "demo/pos_order.xml", 
        "demo/pos_order_line.xml",
        "demo/sale_order.xml",
        "demo/sale_order_line.xml",
        "demo/stock_quant.xml",
        "demo/website_page.xml",
        "demo/website_menu.xml",
        "demo/pos_config.xml",
        "demo/website_theme_apply.xml",
        "demo/sale_order_confirm.xml",
        "demo/website.xml",
    ],
    "demo": [
        
    ],
    "license": "OPL-1",
}
