{
    'name': 'Beauty Parlor',
    'version': '1.0',
    'category': 'Retail',
    'author': 'Odoo S.A.',
    'depends': [
        'account_add_gln',
        'account_online_payment',
        'ai_website',
        'appointment_google_calendar',
        'crm_enterprise',
        'knowledge',
        'l10n_be_reports',
        'pos_enterprise',
        'pos_loyalty',
        'pos_online_payment',
        'sale_edi_ubl',
        'sale_loyalty',
        'survey_crm',
        'website_appointment',
        'website_appointment_crm',
        'wellness_practitioner',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/crm_stage.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/pos_category.xml',
        'data/pos_payment_method.xml',
        'data/uom_uom.xml',
        'data/product_category.xml',
        'data/product_template.xml',
        'data/product_product.xml',
        'data/pos_config.xml',
        'data/product_attribute.xml',
        'data/product_pricelist.xml',
        'data/product_pricelist_item.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
    ],
    'demo': [
        'demo/pos_session.xml',
        'demo/loyalty_program.xml',
        'demo/mail_activity_type.xml',
        'demo/account_analytic_plan.xml',
        'demo/crm_team.xml',
        'demo/website_view.xml',
        'demo/website.xml',
        'demo/appointment_type.xml',
        'demo/pos_order.xml',
        'demo/pos_order_line.xml',
        'demo/website_theme_apply.xml',
        'demo/website_page.xml',
        'demo/res_partner.xml',
        'demo/crm_lead.xml',
        'demo/loyalty_rule.xml',
        'demo/calendar_event.xml',
        'demo/mail_activity.xml',
        'demo/website_menu.xml',
        'demo/ir_attachment_post.xml',
        'demo/loyalty_reward.xml',
    ],
    'license': 'OPL-1',
    'assets': {
            'web.assets_backend': [
                'beauty_parlor/static/src/js/my_tour.js',
            ],
        },
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'static/src/js/my_tour.js',
    ],
    'images': [
        'images/main.png',
    ],
}