{
    "name": "Library",
    "version": "19.0.1.0",
    "category": "Studio",
    "author": "Odoo S.A.",
    "depends": [
        "account_add_gln",
        "account_edi_ubl_cii",
        "account_invoice_extract",
        "account_online_synchronization",
        "documents_account",
        "documents_fsm",
        "documents_hr",
        "documents_product",
        "documents_sign",
        "documents_spreadsheet",
        "hr_homeworking",
        "hr_sign",
        "hr_skills",
        "library",
        "mrp_account",
        "pos_event",
        "pos_hr",
        "pos_loyalty",
        "pos_online_payment_self_order",
        "pos_self_order_preparation_display",
        "pos_self_order_sale",
        "pos_settle_due",
        "project_sale_subscription",
        "project_sms",
        "purchase_stock",
        "sale_account_accountant",
        "sale_crm",
        "sale_loyalty_delivery",
        "sale_pdf_quote_builder",
        "sale_planning",
        "sale_purchase",
        "snailmail_account",
        "theme_bewise",
        "website_appointment_sale_project",
        "website_crm",
        "website_documents",
        "website_event_sale",
        "website_knowledge",
        "website_project",
        "website_sale_autocomplete",
        "website_sale_comparison",
        "website_sale_loyalty",
        "website_sale_mass_mailing",
        "website_sale_wishlist",
        "web_studio"
    ],
    "data": [
        "data/ir_attachment_pre.xml",
        "data/ir_model.xml",
        "data/ir_model_fields.xml",
        "data/ir_ui_view.xml",
        "data/ir_actions_act_window.xml",
        "data/ir_model_access.xml",
        "data/ir_rule.xml",
        "data/documents_document.xml",
        "data/knowledge_cover.xml",
        "data/knowledge_article.xml",
        "data/project_task_type.xml",
        "data/project_project.xml",
        "data/product_template.xml",
        "data/product_product.xml",
        "data/product_attribute.xml",
    ],
    "demo": [
        "demo/website_view.xml",
        "demo/account_analytic_plan.xml",
        "demo/account_analytic_account.xml",
        "demo/resource_resource.xml",
        "demo/project_task.xml",
        "demo/stock_quant.xml",
        "demo/documents_document.xml",
        "demo/project_project.xml",
        "demo/website_theme_apply.xml",
        "demo/website_page.xml",
        "demo/website_menu.xml",
        "demo/website.xml",
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/ir_ui_view.xml",
        "demo/website_view.xml",
    ],
    "license": "OEEL-1",
}
