{
    'name': 'Custom Website',
    'description': 'Custom website module exported from Odoo Website Builder',
    'version': '19.0.1.0.0',
    'author': 'Odoo',
    'license': 'LGPL-3',
    'depends': [
        'website',
        'website_sale',
        'delivery',
        'product',
        'website_event',
        'website_sale_comparison',
        'website_event_sale',
    ],
    'data': [
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template.xml',
        'data/product_template_attribute_line.xml',
        'data/ir_attachment_business.xml',
        'data/event_event.xml',
    ],
    'demo': [
        'demo/website/website.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/views/website_templates.xml',
        'demo/website/server_actions.xml',
        'demo/website/pages/matchmaking.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/match.xml',
        'demo/website/menu.xml',
    ],
}
