{
    'name': 'Metal Fabricator',
    'version': '1.0',
    'category': 'Reatail',
    'author': 'Odoo S.A.',
    'depends': [
        # 'appointment_account_payment',
        'base_industry_data',
        'crm_enterprise',
        'knowledge',
        'project_enterprise',
        'project_mrp_workorder_account',
        'sale_crm',
        'sale_project_stock',
        'sale_purchase_project',
        'website',
    ],
    'data': [
        'data/ir_attachment_pre.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/product_category.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_product.xml',
        'data/project_project_stage.xml',
        'data/sale_order_spreadsheet.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/crm_lead.xml',
        'data/mail_message.xml',
        'data/res_config_setting.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/res_partner.xml',
        'demo/hr_employee.xml',
        'demo/website.xml',
        'demo/account_analytic_account.xml',
        'demo/project_project.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/purchase_order.xml',
        'demo/purchase_order_line.xml',
        'demo/mrp_production.xml',
        'demo/ir_attachment_post.xml',
        'demo/project_task.xml',
        'demo/website_view.xml',
        'demo/website_page.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/product_supplierinfo.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}