{
    'name': 'Freight',
    'version': '1.0',
    'category': 'Services',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'freight',
    'depends': [
        'base_vat',
        'hr_fleet',
        'hr_skills',
        'knowledge',
        'sale',
        'web_grid',
        'web_hierarchy',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/x_freight_stage.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/product_attribute.xml',
        'data/product_category.xml',
        'data/uom_category.xml',
        'data/uom_uom.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/knowledge_tour.xml',
        'data/mail_message.xml',
    ],
    'demo': [
    ],
    'license': 'OPL-1',
    'assets': {
        'web.assets_backend': [
            'freight/static/src/js/my_tour.js',
        ]
    },
    'author': 'Odoo S.A.',
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'images': ['images/main.png'],
}
