{
    'name': 'Real Estate Agency',
    'version': '1.6',
    'category': 'Services',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_crm',
        'base_automation',
        'base_industry_data',
        'crm_enterprise',
        'documents',
        'hr',
        'project_enterprise',
        'sale_commission',
        'sale_crm',
        'sale_project',
        'sign',
        'web_studio',
        'website_crm',
        'website_sale',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_model.xml',
        'data/website_base_unit.xml',
        'data/ir_model_fields.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/crm_team.xml',
        'data/mail_template.xml',
        'data/sign_template.xml',
        'data/sign_item_role.xml',
        'data/sign_item_type.xml',
        'data/sign_item.xml',
        'data/product_public_category.xml',
        'data/product_category.xml',
        'data/sale_commission_plan.xml',
        'data/sale_commission_plan_achievement.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_ui_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
        'data/crm_stage.xml',
        'data/project_task_type.xml',
        'data/project_project.xml',
        'data/product_ribbon.xml',
        'data/product_template.xml',
        'data/ir_attachment_post.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/crm_tag.xml',
        'data/website_view.xml',
        'data/uninstall_hook.xml',
    ],
    'demo': [
        # The website record comes first: it is repointed onto the
        # `website.default_website` xmlid, which later files reference.
        'demo/website/website.xml',
        # Before server_actions.xml: these views override generic view *keys*
        # (website.footer_custom, website.header_call_to_action,
        # website_sale.header_hide_empty_cart_link). The server action toggles
        # those same keys with website_id in context, which copies the generic
        # view on write unless a specific one already exists -> loading it first
        # would leave two specific views per key and the generic arch winning.
        'demo/website/views/website_templates.xml',
        # Before any page: deactivates the generic website.homepage /
        # website.contactus views by copy-on-write.
        'demo/website/server_actions.xml',
        'demo/website/assets.xml',
        'demo/website/images.xml',
        'demo/website/pages/home.xml',
        'demo/website/pages/contactus.xml',
        'demo/website/pages/match.xml',

        'demo/res_company.xml',
        'demo/product_attribute_value.xml',
        'demo/res_partner.xml',
        'demo/hr_department.xml',
        'demo/hr_employee.xml',
        'demo/product_template.xml',
        'demo/product_document.xml',
        'demo/product_image.xml',
        'demo/product_template_attribute_line.xml',
        'demo/product_template_attribute_value.xml',
        'demo/product_product.xml',
        'demo/x_product_template_line.xml',
        'demo/create_link.xml',
        'demo/appointment_type.xml',
        'demo/calendar_event.xml',
        'demo/crm_lead.xml',
        'demo/mail_activity.xml',
        'demo/sale_order.xml',
        'demo/sale_order_line.xml',
        'demo/project_task.xml',
        'demo/sale_commission_plan_user.xml',
        'demo/ir_attachment_post.xml',

        # Substitutes the raw ids the export snapshotted (crm.team, /shop links)
        # once every record it points at exists.
        'demo/website/website_post.xml',
    ],
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "data/uninstall_hook.xml",
        "data/website_view.xml",
        "demo/website/pages/home.xml",
        "demo/website/pages/contactus.xml",
        "demo/website/pages/match.xml",
        "demo/website/views/website_templates.xml",
        "static/src/scss/primary_variables.scss",
    ],
    'application': True,
    'images': ['images/main.png'],
    'license': 'OEEL-1',
    'url': "https://www.odoo.com/trial?industry&selected_app=real_estate",
    'website': "https://www.odoo.com/industries/real-estate-agency",
}
