{
    'name': 'Spa Resort',
    'version': '1.0',
    'category': 'Hospitality',
    'author': 'Odoo S.A.',
    'depends': [
        'appointment_google_calendar',
        'appointment_hr',
        'base_industry_data',
        'contacts',
        'hr_homeworking',
        'hr_skills',
        'knowledge',
        'l10n_be_reports',
        'pos_enterprise',
        'pos_hr',
        'pos_loyalty',
        'pos_online_payment',
        'sale_loyalty_delivery',
        'sale_pdf_quote_builder',
        'sale_planning',
        'survey',
        'website_appointment_sale',
        'website_sale_loyalty',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/ir_attachment_pre.xml',
        'data/pos_category.xml',
        'data/product_product.xml',
        'data/appointment_resource.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/planning_role.xml',
        'data/pos_config.xml',
        'data/mail_message.xml',
        'data/knowledge_article_favorite.xml',
    ],
    'demo': [
        'demo/product_product.xml',
        'demo/appointment_type.xml',
        'demo/loyalty_program.xml',
        'demo/resource_resource.xml',
        'demo/hr_employee.xml',
        'demo/pos_config.xml',
        'demo/website_view.xml',
        'demo/pos_session.xml',
        'demo/res_partner.xml',
        'demo/calendar_event.xml',
        'demo/appointment_booking_line.xml',
        'demo/pos_order.xml',
        'demo/loyalty_reward.xml',
        'demo/pos_order_line.xml',
        'demo/loyalty_rule.xml',
        'demo/sale_order.xml',
        'demo/ir_attachment_post.xml',
        'demo/sale_order_line.xml',
        'demo/website_page.xml',
        'demo/website_menu.xml',
        'demo/website_theme_apply.xml',
        'demo/sale_order_confirm.xml',
        'demo/pos_confirm.xml',
        'demo/payment_provider_demo.xml',
        'demo/website.xml',
    ],
    'license': 'OPL-1',
    'cloc_exclude': [
        'data/knowledge_article.xml',
        'demo/website_view.xml',
    ],
    'images': [
        'images/main.png',
    ],
}
